services:
  vibe:
    build: .
    image: mistral-vibe-uv-tech-test
    stdin_open: true
    tty: true
    volumes:
      - ${PROJECT_PATH}:/repo
      - uv-cache:/root/.cache/uv # UV cache persistence
      - /repo/.venv # Exclude
      - /repo/build
      - /repo/out
      - /repo/vibe
      - ${PROJECT_PATH}/vibe/.vibe:/root/.vibe # Mistral Vibe config
    environment:
      - UV_CACHE_DIR=/root/.cache/uv

volumes:
  uv-cache: